project_id = "rndunloczfpfbubuwffb"

[functions.scan-document]
verify_jwt = true

[functions.ai-document-analysis]
verify_jwt = true

[functions.send-reminder-emails]
verify_jwt = false

[functions.send-immediate-reminder]
verify_jwt = false

[functions.send-bulk-notification]
verify_jwt = false

[functions.chatbot]
verify_jwt = true

[functions.document-renewal-advisor]
verify_jwt = true

[functions.delete-user-account]
verify_jwt = true